variable "env" {}
variable "tags" {}
variable "vpc_cidr_block" {}
variable "public_subnets" {}
variable "azs" {}
variable "db_subnets" {}
variable "web_subnets" {}
variable "account_id" {}
variable "default_route_table_id" {}